camera:
  rgb: "/camera/rgb/image_color"
semantic:
  semantic_label: "semantic_label"
  semantic_label_color: "semantic_label_color"
  action_name: "/semantic_server"
  model_name: 'sparseinst'    # not used
  checkpoint: "sparse_inst_r50vd_base_023caa.pth"
  config: "sparse_inst_r50vd_base.yaml"
  model_scripts: "/media/mxc/bs/SeaSLAM/src/SemanticCNN/script/model/"
  batch_size: 1
client_args:
  bagfile: "/data/tum/rgbd_dataset_freiburg3_walking_xyz.bag"
  save_result: false
  result_path: "/media/mxc/bs/SeaSLAM/src/SemanticCNN/result"
